### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by deniz-blue** [TheAlan404/plasma-client#1]
im making it in issues so we dont have to commit to TODO.md and make conflicts every second etc

- [ ] seperate the code into folders
- [ ] fully translate the code (no more turkish:tm:)
- [ ] implement better plugin api
